### PR TITLE
#25 : added navbar in app.tsx; removed from homepage

### PR DESCRIPTION
**Pull request by pradnyabhukan**
resolves issue #25

### CODE REVIEW

**Review by tymnec — CHANGES_REQUESTED** [review]
@pradnyabhukan please mention which issue your PR Resolves.

**Comment by pradnyabhukan** [comment]
@tymnec I have edited the comment. The PR resolves issue #25

**Comment by tymnec** [comment]
Hmm. 
Whenever you mention an issue you should write Resolves #`issuenumber` just Github rules to link PR with an issue.

Ok but still there are some conflicts. I will fix these conflicts.

@pradnyabhukan Thanks for your contribution.

**Review by tymnec — APPROVED** [review]
Done

**Comment by pradnyabhukan** [comment]
Thank you for letting me know! I am still learning to contribute😅. Thank you 😄 @tymnec

**Pull request merged**
